# ╭─────────────────── Notice ── Notice ── Notice ───────────────────╮
# │ This is a custom Baler workflow file. It is different from the   │
# │ sample workflow suggested for users because it is designed to    │
# │ allow testing Baler. DO NOT COPY THIS FILE; instead, use the     │
# │ sample workflow file named "sample-workflow.yml" from the Baler  │
# │ source repository at https://github.com/caltechlibrary/baler/.   │
# ╰─────────────────── Notice ── Notice ── Notice ───────────────────╯

name: "Bad Link Reporter"

# Configure this section ─────────────────────────────────────────────

env:
  # Files examined by the workflow:
  files: '*.md'

  # Label assigned to issues created by this workflow:
  labels: 'bug'

  # Optional file containing a list of URLs to ignore, one per line:
  ignore: '.github/workflows/ignored-urls.txt'

on:
  schedule:
    # Syntax is: "minute  hour  day-of-month  month  day-of-week"
    - cron: "00 04 * * *"
  pull_request:
    paths: ['**.md']
  push:
    paths:
      - .github/workflows/bad-link-reporter.yml
      - .github/workflows/ignored-urls.txt
  workflow_dispatch:
    inputs:
      files:
        description: "Comma-separated paths or regexp's"
        default: '*.md'
      labels:
        description: "Comma-separated issue labels"
        default: 'bug'
      ignore:
        description: "File containing URLs to ignore"
        default: '.github/workflows/ignored-urls.txt'

# The rest of this file should be left as-is ─────────────────────────

run-name: Test links in files
jobs:
  run-baler:
    name: Run Bad Link Reporter
    runs-on: ubuntu-latest
    steps:
      - uses: caltechlibrary/baler@main
        with:
          files:  ${{github.event.inputs.files  || env.files}}
          labels: ${{github.event.inputs.labels || env.labels}}
          ignore: ${{github.event.inputs.ignore || env.ignore}}
