# Summary: workflow to update the version tag upon new releases.
#
# Copyright 2024 California Institute of Technology.
# License: Modified BSD 3-clause – see file "LICENSE" in the project website.
# Website: https://github.com/caltechlibrary/baler

name: Major tag auto-updater

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      manual_tag:
        description: The release tag
        required: true

run-name: Update major release tag

jobs:
  tag-mover:
    name: Release tag updater
    runs-on: ubuntu-latest

    steps:
    - name: Check out source repository.
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        persist-credentials: true

    - name: Get major version num and update tag.
      shell: bash
      run: |
        set -x
        tag_name=${{github.event.release.tag_name}}
        if [ -n "${{github.event.inputs.manual_tag}}" ]; then
          tag_name=${{github.event.inputs.manual_tag}}
        fi
        major=${tag_name%%.*}
        git config --global user.name '${{github.actor}}'
        git push origin :refs/tags/${major}
        git tag -fa ${major} -m "Update major version tag"
        git push origin --tags
